# Site settings
title: Mohammed Hatem
name: Mohammed Hatem Abu Alhuda
Phone Number : 00201127339006
E-Mail : goliardoqwerty@gmail.com

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/MuhammedHatem
 - title: LinkedIn
   url: https://www.linkedin.com/in/muhammad-hatem-975842151/

#Any buzzword skills you want to include
skills:
 - OOP
 - Design Patterns
 - Algorthims 
 - Python
 - C
 - Data Structures
 - Java
 - PHP
 - HTML
 - SQL
 - Machine learning


#Education is required
education:
 - level: SSP Computer And Communication Engineering Student 
   Graduation : Expected 2020
   school: University of Alexandria

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/58d6c2ffefbcceb560614d2c02ea86f1
   courses:
    - title: Machine Learning Stanford University
    - title: Mathematics for Machine Learning: Linear Algebra Imperial College London


#List of interesting Github repo/projects to include - optional
github:
 - MuhammedHatem/Image-Segmentation-Using-K-Means-Clustring
 - MuhammedHatem/SemEval-2019---Task-6---Subtask-A
 - robhinds/github.com/MuhammedHatem/TM
 - MuhammedHatem/Unix-Simple-Shell
 - github.com/Hassan-Elseoudy/8-Puzzle-Solver As Contributer

  About Me: |
  I am an engineering student with 4 years experience, I am mainly focused on computer vision and data science field, I am working mainly with python and keras framework  and i do have a good experiance as well with C and Java and PHP and HTML <br/><br/>
  I enjoy building Machine Learning Models and it is my main focus and my main interst at the current time and i have worked with building games as well .<br/><br/>

